<a href="https://colab.research.google.com/github/nataliatheodorou123/---/blob/main/%CF%80%CE%B1%CF%81%CE%AC%CE%B4%CE%B5%CE%B9%CE%B3%CE%BC%CE%B1%20%CE%95%CF%81%CE%B3%CE%B1%CF%83%CE%AF%CE%B1%CF%82%201%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Παρακαλώ διευκρινίστε ποιο αρχείο θέλετε να 'μεταφράσετε' σε κώδικα Python και τι είδους μετατροπή επιθυμείτε.
# Για παράδειγμα, θέλετε να διαβάσω ένα αρχείο CSV σε ένα pandas DataFrame, ένα αρχείο JSON σε ένα Python dictionary, κλπ.;
# Επιλέξτε από τα παρακάτω αρχεία:
# - /content/LinearRegressionClassWork2.ipynb
# - /content/sample_data/anscombe.json
# - /content/sample_data/README.md
# - /content/sample_data/california_housing_train.csv
# - /content/sample_data/mnist_train_small.csv
# - /content/sample_data/california_housing_test.csv
# - /content/sample_data/mnist_test.csv

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn import metrics

from sklearn.linear_model import LinearRegression

%matplotlib inline

In [5]:
df=pd.read_csv('advertising.csv')

In [6]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [7]:
df.shape

(200, 4)

In [11]:
X=df.drop('Sales', axis=1)
y=df['Sales']

In [12]:
print("X=",X.shape,"\ny=", y.shape)

X= (200, 3)
y= (200,)

In [14]:
X.head()

      TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [15]:
y.head()

0    22.1
1    10.4
2    12.0
3    16.5
4    17.9
Name: Sales, dtype: float64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [17]:
X_train.shape

(160, 3)

In [18]:
X_test.shape

(40, 3)

In [19]:
model = LinearRegression()

In [20]:
model.fit(X_train, y_train)

LinearRegression()

In [21]:
y_pred = model.predict(X_test)

In [22]:
MAE= metrics.mean_absolute_error(y_test, y_pred)
MSE=metrics.mean_squared_error(y_test, y_pred)
RMSE= np.sqrt(MSE)

In [27]:
print(f'MAE: {MAE}')
print(f'MSE: {MSE}')
print(f'RMSE: {RMSE}')

MAE: 1.3673747989546936
MSE: 2.883932473849332
RMSE: 1.698214495830645